<?php

declare(strict_types=1);

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProdutoSeeder extends Seeder
{
    public function run()
    {
        $produtos = [
            [
                'categoria_id' => 1,
                'nome' => 'Pizza Margherita',
                'slug' => 'pizza-margherita',
                'descricao' => 'Pizza artesanal com molho de tomate, mussarela de búfala, manjericão fresco e azeite de oliva.',
                'preco' => 45.90,
                'preco_promocional' => 39.90,
                'imagem' => 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 1,
            ],
            [
                'categoria_id' => 1,
                'nome' => 'Pizza Pepperoni',
                'slug' => 'pizza-pepperoni',
                'descricao' => 'Pizza com molho de tomate, mussarela, pepperoni fatiado e orégano.',
                'preco' => 52.90,
                'preco_promocional' => null,
                'imagem' => 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 1,
            ],
            [
                'categoria_id' => 1,
                'nome' => 'Pizza Quatro Queijos',
                'slug' => 'pizza-quatro-queijos',
                'descricao' => 'Pizza com mussarela, provolone, parmesão e gorgonzola.',
                'preco' => 49.90,
                'preco_promocional' => 44.90,
                'imagem' => 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 0,
            ],
            [
                'categoria_id' => 2,
                'nome' => 'Hambúrguer Clássico',
                'slug' => 'hamburguer-classico',
                'descricao' => 'Hambúrguer 180g, queijo cheddar, alface, tomate e molho especial.',
                'preco' => 32.90,
                'preco_promocional' => 28.90,
                'imagem' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 1,
            ],
            [
                'categoria_id' => 2,
                'nome' => 'Hambúrguer Duplo',
                'slug' => 'hamburguer-duplo',
                'descricao' => 'Dois hambúrgueres 180g, queijo cheddar, bacon, alface e molho barbecue.',
                'preco' => 42.90,
                'preco_promocional' => null,
                'imagem' => 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 0,
            ],
            [
                'categoria_id' => 3,
                'nome' => 'Sushi Combo 20 Peças',
                'slug' => 'sushi-combo-20-pecas',
                'descricao' => 'Combo com 20 peças variadas de sushi e sashimi.',
                'preco' => 89.90,
                'preco_promocional' => 79.90,
                'imagem' => 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 1,
            ],
            [
                'categoria_id' => 3,
                'nome' => 'Temaki Salmão',
                'slug' => 'temaki-salmao',
                'descricao' => 'Temaki recheado com salmão fresco, cream cheese e cebolinha.',
                'preco' => 28.90,
                'preco_promocional' => null,
                'imagem' => 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 0,
            ],
            [
                'categoria_id' => 4,
                'nome' => 'Lasanha à Bolonhesa',
                'slug' => 'lasanha-a-bolonhesa',
                'descricao' => 'Lasanha caseira com molho bolonhesa, queijo parmesão e manjericão.',
                'preco' => 38.90,
                'preco_promocional' => 34.90,
                'imagem' => 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 1,
            ],
            [
                'categoria_id' => 4,
                'nome' => 'Espaguete Carbonara',
                'slug' => 'espaguete-carbonara',
                'descricao' => 'Espaguete com molho carbonara, bacon crocante e queijo parmesão.',
                'preco' => 35.90,
                'preco_promocional' => null,
                'imagem' => 'https://images.unsplash.com/photo-1645112411342-9665a1dddeb7?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 0,
            ],
            [
                'categoria_id' => 5,
                'nome' => 'Salada Caesar',
                'slug' => 'salada-caesar',
                'descricao' => 'Salada com alface, frango grelhado, croutons, queijo parmesão e molho caesar.',
                'preco' => 29.90,
                'preco_promocional' => 24.90,
                'imagem' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 0,
            ],
            [
                'categoria_id' => 6,
                'nome' => 'Brownie com Sorvete',
                'slug' => 'brownie-com-sorvete',
                'descricao' => 'Brownie de chocolate com sorvete de creme e calda de chocolate.',
                'preco' => 24.90,
                'preco_promocional' => 19.90,
                'imagem' => 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 1,
            ],
            [
                'categoria_id' => 6,
                'nome' => 'Pudim de Leite',
                'slug' => 'pudim-de-leite',
                'descricao' => 'Pudim de leite condensado com calda de caramelo.',
                'preco' => 18.90,
                'preco_promocional' => null,
                'imagem' => 'https://images.unsplash.com/photo-1587313146930-2f7b5c9a6e8c?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 0,
            ],
            [
                'categoria_id' => 7,
                'nome' => 'Suco Detox',
                'slug' => 'suco-detox',
                'descricao' => 'Suco de couve, limão, gengibre e maçã.',
                'preco' => 14.90,
                'preco_promocional' => null,
                'imagem' => 'https://images.unsplash.com/photo-1623062145877-cb4dd6ea2d7f?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 0,
            ],
            [
                'categoria_id' => 7,
                'nome' => 'Refrigerante 2L',
                'slug' => 'refrigerante-2l',
                'descricao' => 'Refrigerante em garrafa PET de 2 litros.',
                'preco' => 9.90,
                'preco_promocional' => 7.90,
                'imagem' => 'https://images.unsplash.com/photo-1580733242127-7cda930cf475?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 0,
            ],
            [
                'categoria_id' => 8,
                'nome' => 'Burrito Mexicano',
                'slug' => 'burrito-mexicano',
                'descricao' => 'Burrito com carne, feijão, arroz, guacamole e sour cream.',
                'preco' => 34.90,
                'preco_promocional' => 29.90,
                'imagem' => 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 1,
            ],
            [
                'categoria_id' => 8,
                'nome' => 'Nachos com Guacamole',
                'slug' => 'nachos-com-guacamole',
                'descricao' => 'Nachos crocantes com guacamole, sour cream e queijo derretido.',
                'preco' => 26.90,
                'preco_promocional' => null,
                'imagem' => 'https://images.unsplash.com/photo-1586016411559-aba8fffda0c7?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 0,
            ],
            [
                'categoria_id' => 9,
                'nome' => 'Camarão na Manteiga',
                'slug' => 'camarao-na-manteiga',
                'descricao' => 'Camarões salteados na manteiga com alho e ervas finas.',
                'preco' => 56.90,
                'preco_promocional' => 49.90,
                'imagem' => 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 1,
            ],
            [
                'categoria_id' => 9,
                'nome' => 'Salada de Frutos do Mar',
                'slug' => 'salada-de-frutos-do-mar',
                'descricao' => 'Salada com camarão, lula, polvo, alface e molho especial.',
                'preco' => 48.90,
                'preco_promocional' => null,
                'imagem' => 'https://images.unsplash.com/photo-1575542944356-dc610e36293a?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 0,
            ],
            [
                'categoria_id' => 10,
                'nome' => 'Café da Manhã Completo',
                'slug' => 'cafe-da-manha-completo',
                'descricao' => 'Café com leite, pão de queijo, bolo de cenoura e suco de laranja.',
                'preco' => 32.90,
                'preco_promocional' => 28.90,
                'imagem' => 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 1,
            ],
            [
                'categoria_id' => 10,
                'nome' => 'Pão de Queijo',
                'slug' => 'pao-de-queijo',
                'descricao' => 'Pão de queijo mineiro feito com queijo meia-cura.',
                'preco' => 14.90,
                'preco_promocional' => 12.90,
                'imagem' => 'https://images.unsplash.com/photo-1625943553852-781c6ddd46f5?w=400&h=300&fit=crop&crop=center',
                'ativo' => 1,
                'destaque' => 0,
            ],
        ];

        foreach ($produtos as $produto) {
            $this->db->table('produtos')->insert($produto);
        }

        echo "✅ " . count($produtos) . " produtos criados com sucesso!\n";
    }
}
